Set Pillow == 7.0.0 since 7.1.0 breaks the unittest
Pillow is a core dependency of ImageIO. The exception reads:

   def testWriteImage(self):
        # test write empty input
        with self.assertRaisesRegex(ValueError, 'Please specify'):
            read_image('')

        # test write invalid file format
        with tempfile.NamedTemporaryFile(suffix='.txt') as fp:
            with self.assertRaisesRegex(ValueError, 'Could not find a format'):
                read_image(fp.name)

        # test read and write valid file formats
        self._assert_write_read('.tif')
        self._assert_write_read('.npy')

        # test read and write .png file
        self._assert_write_read('.png', scale=255)

ValueError: Failed to load image from /tmp/tmpvto2ivhi.png: 'PngImageFile'
object has no attribute '_PngImageFile__frame'